### ISSUE TITLE
crashes well doing entity rendering during start up

### ISSUE THREAD

**Issue by wootaboot** [PlanetTeamSpeakk/MoreCommands#11]
crashes well doing entity rendering during start up
[crash-2020-06-07_14.52.07-client.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/4742775/crash-2020-06-07_14.52.07-client.txt)

**Comment by PlanetTeamSpeakk** [comment]
This appears to be a problem with CreativeCore, or rather, a lack thereof.
Solution: install CreativeCore
