### ISSUE TITLE
Loading pause GUI crashes game

### ISSUE THREAD

**Issue by IcePopPlays** [PlanetTeamSpeakk/MoreCommands#12]
When I try to exit the game, it just shuts down the client and shows the crash report, which is very annoying when you may be playing on a server, or just by yourself.

If you need the crash report, it's attached below.

[crash-2020-07-07_09.28.37-client.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/4885768/crash-2020-07-07_09.28.37-client.txt)

**Comment by PlanetTeamSpeakk** [comment]
You could try playing fair and not using Impact, y'know?
Hacking isn't very nice.
(Just FYI, that does seem to be the problem here, the error is thrown in code in the Impact client, not MoreCommands.)
