### ISSUE TITLE
/hunger command to set hunger and saturation level

### ISSUE THREAD

**Issue by K0-RR** [PlanetTeamSpeakk/MoreCommands#14]
Are you taking suggestions for new features?

**Comment by PlanetTeamSpeakk** [comment]
I sure am, but there's already a /feed command to suite those needs.
Granted, it only allows you to set those values to 20, but it should suite your needs in most cases.

**Comment by K0-RR** [comment]
Ohh, sorry then I didn't find it by ctrl+f and typing hunger on the curseforge description. You may want to add this word.

**Comment by K0-RR** [comment]
Wait I didn't find the /feed command in your description.

**Comment by PlanetTeamSpeakk** [comment]
It is an alias of /heal, it's not documented.
