### ISSUE TITLE
server side crash upon startup

### ISSUE THREAD

**Issue by Moglibogli** [PlanetTeamSpeakk/MoreCommands#15]
[log](https://pastebin.com/U3fUfzNd)

**Comment by PlanetTeamSpeakk** [comment]
You first of all appear to be running an older version of the Fabric API and second, this appears to be a compatibility issue with the mod `reach-entity-attributes` and judging by its name, it is a mod used to alter reach distance which is a feature MoreCommands provides too (using either the `morecommands:reach` attribute or the `/reach` command).

**Comment by Moglibogli** [comment]
There are two mods that might be the one that was causing the crash. tweakeroo and beacon overhaul.

**Comment by Moglibogli** [comment]
also im using the latest verison of the fabric api. unless you mean the loader/launcher. then thats something i cant controll server side

**Comment by Moglibogli** [comment]
huh. when i add this it says its caused by adventure z and later in the log it says something about fabrication but im really not sure what it is. [new log might not actually be different](https://pastebin.com/0MQZzJkc)

**Comment by PlanetTeamSpeakk** [comment]
Compatibility with reach-entity-attributes mod has been fixed.
