### ISSUE TITLE
Incompatible with Tweakeroo

### ISSUE THREAD

**Issue by lumitry** [PlanetTeamSpeakk/MoreCommands#16]
**Not sure where to post this, since it could be an issue with either mod, or both mods, but it seems like MoreCommands and Tweakeroo use the same Mixin and crash when put together:**

[15:01:03] [main/WARN]: @Redirect conflict. Skipping mixins.tweakeroo.json:MixinClientPlayerEntity->@Redirect::onDoesGuiPauseGame(Lnet/minecraft/class_437;)Z with priority 1000, already redirected by morecommands.client_mixins.json:MixinClientPlayerEntity->@Redirect::updateNausea_isPauseScreen(Lnet/minecraft/class_437;)Z with priority 1000

**After that happened, everything in the log (multimc) went red:**

> Failed to start Minecraft:
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> 	... 8 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	... 10 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
> 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.Class.getDeclaredFields0(Native Method)
> 	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
> 	at java.lang.Class.getDeclaredFields(Unknown Source)
> 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
> 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:501)
> 	at net.minecraft.class_128.method_559(class_128.java:101)
> 	at net.minecraft.class_128.<init>(class_128.java:54)
> 	at net.minecraft.class_128.method_24305(class_128.java:425)
> 	at net.minecraft.client.main.Main.main(Main.java:135)
> 	... 15 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onDoesGuiPauseGame(Lnet/minecraft/class_437;)Z in mixins.tweakeroo.json:MixinClientPlayerEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tweakeroo-fabric-1.16.4-refmap.json
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject$failsoft(gist.github.com/517e2d6d4c6a75303721b7e2e995a9f8)
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
> 	... 30 more
> Exiting with -1
> Process exited with code -1.

**Comment by shouxd** [comment]
Yeah, I just had this same issue yesterday. This is terrible as Tweakeroo is a very broadly used mod.

**Comment by PlanetTeamSpeakk** [comment]
> Yeah, I just had this same issue yesterday. This is terrible as Tweakeroo is a very broadly used mod.

I doubt that as it only has a little less than twice as many downloads as my mod does, but nevertheless this issue has been fixed in the latest release and the two mods can now be used together.
