### ISSUE TITLE
Fakeplayer Doesnt Render Overlay

### ISSUE THREAD

**Issue by RyanCR03** [PlanetTeamSpeakk/MoreCommands#18]
Creating a fake player with /fakeplayer doesn't show the overlay layers of the player's skin, cape or any cosmetics added by the firstperson mod
![2021-03-14_17 07 26](https://user-images.githubusercontent.com/32957560/111085964-d1f8fe00-84e7-11eb-8f60-4b430d859f5e.png)
![2021-03-14_17 07 22](https://user-images.githubusercontent.com/32957560/111085965-d2919480-84e7-11eb-8445-0a4a86be6975.png)

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
