### ISSUE TITLE
[Crash] Incompatibility with Forge Multipart CBE

### ISSUE THREAD

**Issue by AlexanderLaptev** [PlanetTeamSpeakk/MoreCommands#2]
MC version: 1.12.2
OS: Windows 10 x64 (8 GB RAM)
Forge version: 14.23.5.2838
Mod version: 2.1 (MoreCommands_2.1_mc1.12-1.12.2.jar)

Mod list: JEI, Optinfine, CodeChicken Lib, Forge Multipart CBE.
Crash occurs during the initialization state.
[Crash log attached](https://github.com/PlanetTeamSpeakk/MoreCommands/files/3293441/crash-2019-06-15_21.47.24-client.txt)

If you need any other information I could provide, feel free to ask.

**Comment by PlanetTeamSpeakk** [comment]
Was fixed quite some time ago, so I should probably close this.
