### ISSUE TITLE
Error when connecting

### ISSUE THREAD

**Issue by wh0oo** [PlanetTeamSpeakk/MoreCommands#20]
![erroor](https://user-images.githubusercontent.com/45668419/112731314-7164ba80-8f04-11eb-8ee3-905e9321fbb7.PNG)
Server starts fine, running on linux, no errors, but I cannot join.

**Comment by wh0oo** [comment]
From my game log:

[13:51:32] [Netty Client IO #2/ERROR]: Could not deserialize morecommands:registry_argument

**Comment by PlanetTeamSpeakk** [comment]
Are you sure that first error is caused by MoreCommands? Doesn't seem like anything my mod would cause.
Regarding the second one, imma need some more info to go with that if you have any cuz I'm not sure if the two are related and even if they are, that still doesn't get me very far.

**Comment by wh0oo** [comment]
Hey, sorry for my vagueness.

I am using morecommands on a remote server running the latest (as of my typing) version of fabricmc.  I am also running carpet (also latest version) (in a very limited capacity).

The screenshot above corresponds to the error message I posted.  There is just this, in my local log:

[13:51:29] [Render thread/INFO]: Connecting to xx.xx.xx.xx., 25565
[13:51:32] [Netty Client IO #2/ERROR]: Could not deserialize morecommands:registry_argument
[13:51:33] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', account .....

The logs on the server only show the connection happening as normal.



Finally, yes, this is caused by morecommands.  If I remove it, I can join the server.  

I am going to try it without carpet to see if there is an incompatability, but yes, its morecommands that's causing the issue on joining.

**Comment by wh0oo** [comment]
Following up, I tried running just this mod alone, no other mods to conflict, and still a no-go.

**Comment by kotaskyy** [comment]
im having the exact issue.. when this mod is loaded and i try to join, i get kicked immediately, and when i remove the mod everything works fine. :l any possible fixes?
