### ISSUE TITLE
Various mod incompatibilities

### ISSUE THREAD

**Issue by Alkiasan** [PlanetTeamSpeakk/MoreCommands#21]
Hi, trying to run this alongside some other mods and getting a huge crashlog on startup,

Using the latest ver with origins compatibility, but the crash log speaks about incompatibility with origins, emotecraft, voicechat, waila, etc.

Is this possible to fix?

[crash-2021-04-22_16.56.37-client.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/6359627/crash-2021-04-22_16.56.37-client.txt)

**Comment by PlanetTeamSpeakk** [comment]
I suppose it's possible to fix, but I must admit, at first sight, I haven't got a clue.

**Comment by snowboundmage2** [comment]
This mod conflicts with BetterEnd. Apparently redirects an important function that BetterEnd mixin Needs

[latest - Copy.log](https://github.com/PlanetTeamSpeakk/MoreCommands/files/6804135/latest.-.Copy.log)

this might help you find whats what
