### ISSUE TITLE
Server-side Mod

### ISSUE THREAD

**Issue by ghost** [PlanetTeamSpeakk/MoreCommands#22]
Hi,

I understand that this is unlikely to happen, but please could you consider creating a server-side mod(Fabric 1.16.5) with all of the features that can be done server-side.
I really want to use this on my server, but the server is server-side only and this mod is needed on the client as well as the server.

**Comment by PlanetTeamSpeakk** [comment]
I doubt I'll make a standalone mod, but I suppose I could _try_ to add a config option of sorts that makes the mod able to only be run on the server side.

**Comment by ghost** [comment]
That would be great!
Thank you for considering it!

**Comment by PlanetTeamSpeakk** [comment]
Feature added in upcoming release. (Do mind it's still beta, please report any issues you're having.)
