### ISSUE TITLE
/cannon crash server + internal error while connecting

### ISSUE THREAD

**Issue by THE-MecanOStarCrafter** [PlanetTeamSpeakk/MoreCommands#23]
I've did the /cannon command on my server and the server crashed when i did it. since then when im trying to connect it say that there is an internal server error.

**Comment by PlanetTeamSpeakk** [comment]
Can you be more specific about the internal error? What error do you get?
I also personally don't have any issues with using the cannon command on servers, so if you could provide an error log for that, if that's still an issue at least, that'd be appreciated as well.
