### ISSUE TITLE
Implement fabric permission API

### ISSUE THREAD

**Issue by ghost** [PlanetTeamSpeakk/MoreCommands#27]
I am trying to use your mod for ranks on my server and I found that you do not use fabric permissions API and instead just use OP and not OP to see who should have what. I was wondering if there would be a way that you can add this to your mod. Thank you!

**Comment by MenacingPerson** [comment]
Which permissions api?
https://github.com/lucko/fabric-permissions-api
https://github.com/FabLabsMC/Permissions
The first one is by the person who made luckperms, I recommend the first one.
There is also one more:
https://github.com/Patbox/ServerPermissionsAPI
which provides more functionality.

**Comment by ghost** [comment]
I was thinking that fabric permissions api would be the best option. But it would be up to the author.

**Comment by PlanetTeamSpeakk** [comment]
This has been implemented in 3.8.
