### ISSUE TITLE
/enchantmax causes crash when hovering over the item

### ISSUE THREAD

**Issue by karstenzip** [PlanetTeamSpeakk/MoreCommands#29]
When using /enchantmax on an item and hovering over that item causes the game to crash

The crash report created by NotEnoughCrashes:
[https://gist.githubusercontent.com/natanfudge/71dc2cbd22ef912c740d51330d46094f/raw/824b3f30dc6aa26a466ba98baf52dde22f444663/crash.txt](https://gist.githubusercontent.com/natanfudge/71dc2cbd22ef912c740d51330d46094f/raw/824b3f30dc6aa26a466ba98baf52dde22f444663/crash.txt)

Edit: It also causes player invisiblity and no block breaking particles. A game restart fixes the player invisiblity and no breaking particles

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
