### ISSUE TITLE
[1.12.2] Class not found exception plus crash with VanillaFix

### ISSUE THREAD

**Issue by DefinitelyNotFred** [PlanetTeamSpeakk/MoreCommands#3]
I'm using the latest version of Forge for 1.12.2 (version 14.23.5.2838), not the recommended version, to meet the requirements of other mods. When using the VanillaFix mod there is a crash but if not using the VanillaFix mod there is no crash, just the error in the logs.

More Commands error log: https://gist.github.com/DefinitelyNotFred/e5e69ce21249ed55da1cb9b1de0cc021

More Commands crash log with VanillaFix: https://gist.github.com/DefinitelyNotFred/d3ec4bf1d60a8dc6f144f8848928b79e

**Comment by PlanetTeamSpeakk** [comment]
Also fixed by not using Reflections.
