### ISSUE TITLE
A more advanced /fakeplayer command and maybe /entity?

### ISSUE THREAD

**Issue by karstenzip** [PlanetTeamSpeakk/MoreCommands#32]
**This is a feature request**
I would really like 2 things:

1. A more advanced /fakeplayer command
If you create a fake player, its assigns a id to it (starting with 0).
If you do "/fakeplayer editor (id)" it opens a GUI where you can customize the fake player. In the GUI there are buttons (to other GUI's) that say things you can edit like:
- Path
- Invulnerable
- Health
- Facing
- Effects
- Can enter portals (Yes/No)
- Inventory (seperate row for armor, main-hand and off-hand items. Ability to toggle whether players can acces the inventory, restrict acces to inventory for specific players)
- Owner (Follow Yes/No, Attack other players Yes/No, Attack other mobs Yes/No)

2. A /entity command
Simular to the /fakeplayer command (and suggestion) but for entities but with:
- Ability to change entity type
- Ability to change properties of that entity (like things mentioned in suggestion 1)

**Comment by PlanetTeamSpeakk** [comment]
So you basically want the Custom NPCs mod but for newer Minecraft versions? I could do that one but I'd probably make it a standalone mod.

**Comment by karstenzip** [comment]
Yeah basically. But since there is already a /fakeplayer command I thought it _might_ fit in

**Comment by PlanetTeamSpeakk** [comment]
I have decided not to add this as such a mod already exists now.
