### ISSUE TITLE
/enchant @s (any enchant) 0 crashes game on hover

### ISSUE THREAD

**Issue by karstenzip** [PlanetTeamSpeakk/MoreCommands#33]
When you enchant anything with something level 0 e.g. /enchant @s sharpness 0 it crashes the game when you hover over the item.
Here is the crash report generated by NotEnoughCrashes:
[https://gist.githubusercontent.com/natanfudge/83640c127c501a9649ccf3882669c2f3/raw/e9b4059771cf458312c16cc8050d27eb348348fa/crash.txt](https://gist.githubusercontent.com/natanfudge/83640c127c501a9649ccf3882669c2f3/raw/e9b4059771cf458312c16cc8050d27eb348348fa/crash.txt)

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
