### ISSUE TITLE
MoreCommands doesn't work with Aternos Servers

### ISSUE THREAD

**Issue by C47UMX** [PlanetTeamSpeakk/MoreCommands#34]
Whenever I try to load morecommands onto my Aternos Server, It gives me the message 'Could not deserialize morecommands:limited_string'. I have fabricAPI and fabric installed on the server. Client side, i see: 
![image](https://user-images.githubusercontent.com/88086119/127317098-77de9005-169b-45c0-9c13-b6b3d1cfb896.png)

**Comment by PlanetTeamSpeakk** [comment]
Do you have the mod installed on both the server and the client?
