### ISSUE TITLE
Glitched Custom Swords

### ISSUE THREAD

**Issue by mrthethatone** [PlanetTeamSpeakk/MoreCommands#35]
I downloaded morecommands after seeing that there was a fabric 1.16.5 version, but when I loaded up the game I saw this (kinda) in my inventory 

![weird](https://user-images.githubusercontent.com/80386883/127744998-02c867d6-c7d4-4070-9e09-024c6fd28c82.PNG)

And this is what it is meant to look like:

![normal](https://user-images.githubusercontent.com/80386883/127745006-1d0a9e48-7c31-428f-8fe4-87c55d3ebb45.PNG)

What happened?

Side note: Its not only the inventory icons but also the actual model in game, its weird.

**Comment by PlanetTeamSpeakk** [comment]
This issue can be temporarily resolved by disabling the Fix Item Seams rendering client option, but I honestly don't know what happened here either.

**Comment by mrthethatone** [comment]
How do you disable that?

**Comment by quank123wip** [comment]
Yes I have met a issue like this but it glitched Minecraft Transit Railway

**Comment by quank123wip** [comment]
> How do you disable that?

In client options txt file.

**Comment by PlanetTeamSpeakk** [comment]
There's an easier method which is by going to Minecraft's settings menu in game and pressing the MoreCommands button.

**Comment by PlanetTeamSpeakk** [comment]
It would appear this bug happens to items whose models have a `display` property, others are fine. So if I cannot fix this issue, I can just ignore models that have a `display` property.

**Comment by PlanetTeamSpeakk** [comment]
'Fixed' in the upcoming release, couldn't figure out how to do it so I now just ignore items with a `display` property meaning that those swords will still have seams.
