### ISSUE TITLE
Crashes on startup [1.1.7.1]

### ISSUE THREAD

**Issue by itsdinkd** [PlanetTeamSpeakk/MoreCommands#36]
Client crash on startup
latest version of mod

---- Minecraft Crash Report ----
// You're mean.

Time: 8/4/21, 11:22 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'morecommands'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.redirect$znc000$catchFabricInit(class_310.java:7064)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1076.method_4669()" because the return value of "net.minecraft.class_310.method_1526()" is null
	at net.minecraft.class_2477.localvar$bke000$modifyLanguage(class_2477.java:1516)
	at net.minecraft.class_2477.method_29427(class_2477.java)
	at com.ptsmods.morecommands.MoreCommandsClient.onInitializeClient(MoreCommandsClient.java:157)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$eio000$fillPatchouliContext(class_128.java:1521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$eio000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:37)
	at net.minecraft.class_310.redirect$znc000$catchFabricInit(class_310.java:7066)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 173875280 bytes (165 MiB) / 1006632960 bytes (960 MiB) up to 10166992896 bytes (9696 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e87
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 36699.46
	Virtual memory used (MB): 27166.72
	Swap memory total (MB): 4000.00
	Swap memory used (MB): 398.14
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9696m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.2.10
		agape_space: Space Dimensions 0.2.11
		ambientenvironment: Ambient Environment 6.0.21
		amecsapi: Amecs API 1.1.5+mc21w16a
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		apoli: Apoli 1.0.4
		appleskin: AppleSkin mc1.17-2.1.2
		aqupd: Caracal mob 1.17-1.2.2
		architectury: Architectury 2.3.23
		artofalchemy: Art of Alchemy: Memoriam 1.2.0+1.17.1
		audiooutput: AudioOutput 0.0.4
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.5
		balm-fabric: Balm 1.3.0+0
		bclib: BCLib 0.2.4
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterbiomeblend: Better Biome Blend 1.17.0-1.2.7-fabric
		betterend: Better End 0.10.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		blockus: Blockus 2.2.7+1.17.1
		blur: Blur (Fabric) 2.1.0
		calio: Calio 1.0.2
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0-nightly.1.17-pre2
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.20.0+build.633
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chesttracker: Chest Tracker 1.0.11
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps fabric-1.17.1-7.0.4
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftingtweaks: Crafting Tweaks 13.0.0+0
		craftpresence: CraftPresence 1.8.2
		croptopia: Croptopia 1.6.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		customportalapi: Custom Portal Api 0.0.1-beta39-1.17
		dankstorage: Dank Storage 2.1-1.17.1
		defaultsettings: DefaultSettings 3.0.3
		detailab: Detail Armor Bar 1.2.3+1.17.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dual_riders: DualRiders 1.0.5
		emagnet: E Magnet 1.2.3
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		expandedstorage: Expanded Storage 7.0.0
		explorerscompass: Explorer's Compass 1.17.1-2.0.1-fabric
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricenchantments: Fabric Enchantments 0.4.1
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fasttransferlib: Fast Transfer Lib 0.5.5
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		gamemodeoverhaul: GamemodeOverhaul 1.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.11
		gobber2: Gobber2 2.4.35
		hctm-base: HCTM Base 3.6.2
		heartbond: Heartbond 1.1.0
		hologram-api: Hologram API 0.1.2+1.17.1
		hookshot: Hookshot 17.0
		horseinfo: Horse Info 0.3.0-1.17
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		illuminations: Illuminations 1.6.3
		incantationem: Incantationem 1.1.1+1.17.1
		inventoryprofilesnext: Inventory Profiles Next 0.8.4
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		justenoughkeys: Just Enough Keys 0.2.1
		kibe: Kibe 1.8-BETA+1.17
		ksrch: Keybind Search 1.0.0
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1605.3.10-build.9999
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.3.0
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.3.9.1
		lithium: Lithium 0.7.3
		logical_zoom: Logical Zoom 0.0.11
		ltr: LilTaterReloaded 1.1.15+1.17.1
		magick: Magick: Potions and Pearls 1.0.5
		malilib: MaLiLib 0.10.0-dev.24
		mcda: MC Dungeons Armors 1.7.6
		mcdw: MC Dungeons Weapons 3.3.4
		megane: megane 5.1.2
		megane-base: megane-base 5.1.2
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.1.2+0.4.2
		megane-kibe: megane-kibe 5.1.2+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.1.2+0.9.0
		megane-runtime: megane-runtime 5.1.2
		megane-team-reborn-energy: megane-team-reborn-energy 5.1.2+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.1.2+5.0.2-beta-build.38
		megane-vanilla: megane-vanilla 5.1.2+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.1.2+1.1.1
		minecraft: Minecraft 1.17.1
		minecraftcapes: MinecraftCapes Mod 11.0.1
		mining_dims: Mining Dimensions 1.1.11
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.4
		morecommands: MoreCommands 3.8.1
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		noanglebrackets: NoAngleBrackets 1.1.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17-54-FABRIC
		placeholder-api: Fabric Placeholder API 1.0.1+1.17
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.0-pre9+1.17.1
		prefab: Prefab 2.1.0
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		ratsmischief: Rat's Mischief 1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.5-beta+build.85
		redbits: Red Bits 1.10.0
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		repurposed_structures: Repurposed Structures 2.1.8+1.17.1
		resourceful_tools: Resourceful Tools 1.1.19
		rhino: Rhino 1605.1.1-build.23
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		rpgstats: RPGStats 4.1.8+1.17.1
		rswires: RSWires 4.11.2
		satin: Satin 1.6.0-nightly.1.17-pre3
		schmucks: Schmucks 1.4.0
		server_translations_api: Server Translations API 1.4.5+1.17
		servertick: Server Tick 1.5
		sgui: SGui 1.0.0-rc3-1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		simple_backpack: SimpleBackpack 1.1.17
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.3
		spruceui: SpruceUI 3.2.0+1.17
		statuseffecttimer: Status Effect Timer 1.0.3
		stoneholm: Stoneholm 1.3
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.5-beta+build.85
		things: Things 0.2.2
		toms_storage: Tom's Simple Storage Mod 1.1.13-1.17.1
		toolstats: Tool Stats 2.0.1
		torcherino: Torcherino 15.1.0-alpha.3
		trinkets: Trinkets 3.0.2
		truerooms: True Secret Rooms 1.1.5
		universal-graves: Universal Graves 1.0.7+1.17.1
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		ward_blocks: Ward Blocks 1.1.7
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.0.3
		whereisit: Where Is It 1.13.3
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.1.2
		witherite: Witherite 0.0.8-hotfix
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.14.1
		xaeroworldmap: Xaero's World Map 1.16.0
		xhp: xhp 1.0.9
		yungsapi: YUNG's API 1.17-Fabric-14
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: MoreCommands (morecommands), Fabric Loader (fabricloader)

**Comment by PlanetTeamSpeakk** [comment]
Seems like this is a compatibility issue. I can easily fix this tho, so expect it to be fixed in the next release.

**Comment by PlanetTeamSpeakk** [comment]
I believe I have fixed this issue in the upcoming release, if not, feel free to reopen it.
