### ISSUE TITLE
MoreCommands Crashes 1.17.1 Fabric Server

### ISSUE THREAD

**Issue by ShaKabosh** [PlanetTeamSpeakk/MoreCommands#39]
I have tried multiple versions of MoreCommands on my Fabric 1.17.1 Server, however they all cause a crash.

Crash Log: https://pastebin.com/a2pgxBHQ

**Comment by PlanetTeamSpeakk** [comment]
It would seem this is not caused by MoreCommands and might even not be due to a mod at all, but if it is, have a look at some mod called 'fic' (might be an acronym for its full name).

**Comment by ShaKabosh** [comment]
I don't think this is likely, as when I start the server _without_ MoreCommands, it does not crash without MoreCommands. Furthermore, I found the last entry marked [main/FATAL] was this: https://pastebin.com/bnb4Bfe2
Here is the full list of mods: https://pastebin.com/4x0Sk1DV

Sorry for the late response.

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
