### ISSUE TITLE
Error Minecraft Crash

### ISSUE THREAD

**Issue by ReisenYT** [PlanetTeamSpeakk/MoreCommands#40]
[crash-2021-09-05_21.14.05-client.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/7112574/crash-2021-09-05_21.14.05-client.txt)
This happen today. Can someone help me?

**Comment by PlanetTeamSpeakk** [comment]
This has already been fixed in an upcoming release. It's some sort of compatibility issue.
