### ISSUE TITLE
MoreCommands can't let me log in into Minecraft

### ISSUE THREAD

**Issue by Ratorox** [PlanetTeamSpeakk/MoreCommands#41]
When I start the server, it doesn't crash, but when I enter it give me this error :

"Connections Lost
 Registry remapping failed: Received ID map for minecraft:sound_event contains IDs 
 unknow to the receiver!
 
 - morecommands:copy
 - morecommands:easteregg
"

How do I fix?

**Comment by PlanetTeamSpeakk** [comment]
This mod has to be installed on both the client and the server for it to work.
