### ISSUE TITLE
Edge of player reach blocks not breaking

### ISSUE THREAD

**Issue by phlafoo** [PlanetTeamSpeakk/MoreCommands#42]
I am using minecraft 1.17.1.
I am using MoreCommands version 3.8.1 with no other mods (only fabric loader and fabric API).

If a block is near the limit of my reach then it will not break. I tested this using a fresh install and without running any MoreCommands commands. Applies to creative and survival. Using the /reach command to shorten or lengthen my reach does not help, the blocks near the limit of my reach are always unbreakable

https://user-images.githubusercontent.com/52980561/133704036-3677b73c-98ff-4155-b021-e21d1c3bde10.mp4

.

**Comment by PlanetTeamSpeakk** [comment]
This is more or less a known issue, but as it's not that big of a deal, I haven't made an attempt at fixing it yet. It's quite easy to fix tho and it would also prevent the console from being spammed as much when breaking blocks while moving, so I'll have a look.

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
