### ISSUE TITLE
Minecraft crashes with MoreCommands and Wurst Client

### ISSUE THREAD

**Issue by yentdevries** [PlanetTeamSpeakk/MoreCommands#45]
When i try to launch Minecraft with MoreCommands mod and Wurst Client both installed, it crashes with exit code 0. I have fabric loader and Fabric API.

How can this be fixed?

**Comment by PlanetTeamSpeakk** [comment]
Well, first of all, this can be fixed by not hacking :). Second, I'll have a look at it.

**Comment by PlanetTeamSpeakk** [comment]
Could you tell me what version of Wurst, MoreCommands, Minecraft and Fabric you're using?  
I cannot replicate this issue with the upcoming release and Wurst v7.15.3 on Minecraft 1.17 with Fabric 0.11.6.
