### ISSUE TITLE
Aternos Resource Pack

### ISSUE THREAD

**Issue by thereal-wumpus** [PlanetTeamSpeakk/MoreCommands#48]
so i apply this recourse pack https://www.dropbox.com/s/rs9i82apui8q4j3/why.zip?dl=1
changed the =0 to =1 (as says the tutorial)
<img width="1833" alt="Screen Shot 2021-11-16 at 2 06 15 PM" src="https://user-images.githubusercontent.com/94407789/141877671-57d7221f-67b1-4603-8f89-7df8470e54eb.png">
and it shows this

**Comment by PlanetTeamSpeakk** [comment]
Is there any error in the console/log related to this?

**Comment by thereal-wumpus** [comment]
No, as far as I am aware

**Comment by thereal-wumpus** [comment]
@PlanetTeamSpeakk ???

**Comment by PlanetTeamSpeakk** [comment]
Does it work without MoreCommands and if so, could you send me the log anyway just to be sure?

**Comment by PlanetTeamSpeakk** [comment]
I can't really solve this issue if I there's no error and I can't replicate it.

**Comment by thereal-wumpus** [comment]
Yes it does work without MoreCommands

**Comment by thereal-wumpus** [comment]
The log of it with MoreCommands installed?

**Comment by thereal-wumpus** [comment]
Well thats weird, I just logged in to Aternos and it says there is no such thing as MoreCommands in the mods area

**Comment by thereal-wumpus** [comment]
Hello?

**Comment by PlanetTeamSpeakk** [comment]
> Well thats weird, I just logged in to Aternos and it says there is no such thing as MoreCommands in the mods area

Idk, I don't put it there, they do.

**Comment by PlanetTeamSpeakk** [comment]
> The log of it with MoreCommands installed?

Yes, obviously

**Comment by thereal-wumpus** [comment]
I can't find the log but this thread isnt really important now

**Comment by thereal-wumpus** [comment]
I started using Minefort
