### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by karstenzip** [PlanetTeamSpeakk/MoreCommands#50]
I updated to Fabric 1.12.5 on version 1.17.1 but Minecraft crashed. Running Minecraft without MoreCommands does work.
Here is the crash report: [latest.log](https://github.com/PlanetTeamSpeakk/MoreCommands/files/7610059/latest.log)

**Comment by PlanetTeamSpeakk** [comment]
This seems to be an issue with Sodium somehow, but it is known that MoreCommands does not work with Fabric 12.x as of right now, this has already been fixed in an upcoming release, however.
