### ISSUE TITLE
Game Crushed with More Commands

### ISSUE THREAD

**Issue by FedDragon1** [PlanetTeamSpeakk/MoreCommands#51]
I tried to use this mod on 1.17.1 fabric server, but it crushes with code 0
Using java 16.0.2
Here is the log from Minecraft: [latest.log](https://github.com/PlanetTeamSpeakk/MoreCommands/files/7622825/latest.log)

Mod List:
Fabric API 0.43.0
LuckPerms 5.3.9
More Commands 3.8.1

**Comment by PlanetTeamSpeakk** [comment]
This is a known issue and has been fixed in an upcoming release.
For now, you can downgrade to Fabric 11.x instead of 12.x to fix this.
