### ISSUE TITLE
Getting the following "Errors in currently selected datapacks prevented world from loading" when trying to open an existing world

### ISSUE THREAD

**Issue by VedantParashar** [PlanetTeamSpeakk/MoreCommands#52]
this occurs only when I try open the world with this mod no other mod causes this issue does the mod create a datapack folder cause I dont have any datapacks

**Comment by PlanetTeamSpeakk** [comment]
A message like this should come with an error in the console, so could you send your log so I can have a look?

**Comment by VedantParashar** [comment]
[latest.log](https://github.com/PlanetTeamSpeakk/MoreCommands/files/7724757/latest.log)
 here you go mate also correct me if this is the wrong file

**Comment by PlanetTeamSpeakk** [comment]
Seems like an incompatibility issue with Carpet, I'll have a look at this later.

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
