### ISSUE TITLE
1.18.1 singleplayer: What is "mm"?

### ISSUE THREAD

**Issue by ayellowlizard** [PlanetTeamSpeakk/MoreCommands#56]
![image](https://user-images.githubusercontent.com/89428651/147195392-6f45411a-d123-4aca-9ad9-905c49eca9a7.png)
Every time I try to start up my minecraft, this pops up.
I've tried looking through the dependency listing and the installation guide, but there's nothing except fabric api and luckperms. Fabric API, I already have installed, luckperms, it said it was optional, so I didn't install it.
Sorry if this is really obvious or a duplicate... I just can't find anything else.

**Comment by wlm3201** [comment]
Try this.
https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip

**Comment by ayellowlizard** [comment]
Thanks.

**Comment by PlanetTeamSpeakk** [comment]
This issue will be fixed shortly, likely tomorrow OK Christmas.
Downgrading to 3.9.1 also fixes this issue.

For those who want to go a little deeper down the rabbit hole, you can also fix it by opening the jar file with something like WinRAR, open the `fabric.mod.json`file with a text editor like Notepad or Notepad++ and remove the line that says `"mm": ">=2.3"` in the `requires`section near the end of the file and also remove the comma on the line above it.
