### ISSUE TITLE
Cannot get 3.9.2

### ISSUE THREAD

**Issue by MarioMastr** [PlanetTeamSpeakk/MoreCommands#59]
I keep on seeing all these people with "3.9.2" of morecommands and i am trying to get it to see if it might solve my problems (which i mentioned in a now closed issue), and for the life of me i cannot do it.

**Comment by PlanetTeamSpeakk** [comment]
I archived 3.9.2 since it had issues that prevented users from even starting the game. If you still have issues with 3.9.1 of the mod that you addressed in a closed issue and the issues are not addressed in the 3.9.2 commit, feel free to create a new issue and I'll have another look at it.
