### ISSUE TITLE
Game crashes ever time while loading this mod. ):

### ISSUE THREAD

**Issue by SpyTheMeme** [PlanetTeamSpeakk/MoreCommands#6]
Here is my crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.10.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  McLib core mod (mclib-1.0.2-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.151.jar)
  Extended Reach core mod (extendedreach-1.0-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  Quark Plugin (Quark-r1.5-166.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/26/19 5:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/common/items/ItemShader
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/common/items/ItemShader
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.common.items.ItemShader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/shader/IShaderItem
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.api.shader.IShaderItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 710804096 bytes (677 MB) / 2147483648 bytes (2048 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E4_pre4 117 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                            | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LC    | mcp                               | 9.42                     | minecraft.jar                                     | None                                     |
	| LC    | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                             | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | opencomputers|core                | 1.7.4.153                | minecraft.jar                                     | None                                     |
	| LC    | tnt_utilities_core                | 1.2.3                    | minecraft.jar                                     | None                                     |
	| LC    | dsurroundcore                     | 3.5.4.3                  | minecraft.jar                                     | None                                     |
	| LC    | actuallyadditions                 | 1.12.2-r149              | ActuallyAdditions-1.12.2-r149.jar                 | None                                     |
	| LC    | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LC    | jei                               | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LC    | botania                           | r1.10-361                | Botania+r1.10-361.jar                             | None                                     |
	| LC    | aiotbotania                       | 0.7                      | aiotbotania-0.7.jar                               | None                                     |
	| LC    | placebo                           | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                          | None                                     |
	| LC    | apotheosis                        | 1.10.2                   | Apotheosis-1.12.2-1.10.2.jar                      | None                                     |
	| LC    | astralsorcery                     | 1.10.19                  | astralsorcery-1.12.2-1.10.19.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LC    | betteranimals                     | 5.2.1                    | betteranimals-5.2.1.jar                           | None                                     |
	| LC    | quark                             | r1.5-166                 | Quark-r1.5-166.jar                                | None                                     |
	| LC    | autoreglib                        | 1.3-31                   | AutoRegLib-1.3-31.jar                             | None                                     |
	| LC    | betterbedrockgen                  | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar             | None                                     |
	| LC    | forgelin                          | 1.8.3                    | Forgelin-1.8.3.jar                                | None                                     |
	| LC    | betterportals                     | 0.1.6                    | betterportals-0.1.6.jar                           | None                                     |
	| LC    | biomesoplenty                     | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar     | None                                     |
	| LC    | byg                               | 1.6.8                    | BiomesYouGo_1.6.8b1.jar                           | None                                     |
	| LC    | buildinggadgets                   | 2.7.1                    | BuildingGadgets-2.7.1.jar                         | None                                     |
	| LC    | carryon                           | 1.12.2                   | CarryOn+MC1.12.2+v1.12.2.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LC    | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LC    | chiselsandbits                    | 14.33                    | chiselsandbits-14.33.jar                          | None                                     |
	| LC    | classiccombat                     | 1.0.1                    | ClassicCombat-1.0.1.jar                           | None                                     |
	| LC    | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                          | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LC    | cofhworld                         | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | controlling                       | 3.0.7                    | Controlling-3.0.7.jar                             | None                                     |
	| LC    | craftingtweaks                    | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                   | None                                     |
	| LC    | ctm                               | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LC    | nei                               | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | endercore                         | 1.12.2-0.5.59            | EnderCore-1.12.2-0.5.59.jar                       | None                                     |
	| LC    | thermalfoundation                 | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion                  | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                           | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LC    | projecte                          | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                       | None                                     |
	| LC    | enderiointegrationtic             | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | twilightforest                    | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                  | None                                     |
	| LC    | p455w0rdslib                      | 2.2.151                  | p455w0rdslib-1.12.2-2.2.151.jar                   | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LC    | theoneprobe                       | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                       | None                                     |
	| LC    | danknull                          | 1.5.71                   | DankNull-1.12.2-1.5.71.jar                        | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LC    | enderiobase                       | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | enderioconduits                   | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | opencomputers                     | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar              | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | refinedstorage                    | 1.6.14                   | refinedstorage-1.6.14.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LC    | enderioconduitsrefinedstorage     | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | enderiointegrationforestry        | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | enderiointegrationticlate         | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | enderiomachines                   | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | enderiopowertools                 | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
	| LC    | eqs                               | 1.0.3                    | EquivalentStorage-1.0.3.jar                       | None                                     |
	| LC    | mclib                             | 1.0.2                    | mclib-1.0.2-1.12.2.jar                            | None                                     |
	| LC    | extendedreach                     | 1.0                      | extendedreach-1.0-1.12.2.jar                      | None                                     |
	| LC    | extrabitmanipulation              | 1.12.2-3.4.1             | ExtraBitManipulation-1.12.2-3.4.1.jar             | None                                     |
	| LC    | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LC    | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                             | None                                     |
	| LC    | ghostsexplosives                  | 2.3.0 - MC 1.12.2        | Ghost's+Explosives+2.3.0+-+MC1.12.2.jar           | None                                     |
	| LC    | icbmclassic                       | 1.12.2-3.3.0.63          | ICBM-classic-1.12.2-3.3.0b63.jar                  | None                                     |
	| LC    | llibrary                          | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire                        | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                       | None                                     |
	| LC    | ichunutil                         | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | igauntlet                         | 3.6.1                    | IGauntlet-1.12.2-3.6.1.jar                        | None                                     |
	| LC    | inventorypets                     | 2.0.1                    | inventorypets-1.12-2.0.1.jar                      | None                                     |
	| LC    | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.69.845.jar                   | None                                     |
	| LC    | journeymap                        | 1.12.2-5.5.5b7           | journeymap-1.12.2-5.5.5b7.jar                     | None                                     |
	| LC    | mcjtylib_ng                       | 3.5.3                    | mcjtylib-1.12-3.5.3.jar                           | None                                     |
	| LC    | testdummy                         | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                        | None                                     |
	| LC    | numina                            | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                          | None                                     |
	| LC    | railcraft                         | 12.0.0                   | railcraft-12.0.0.jar                              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | powersuits                        | 1.12.2-1.0.44            | ModularPowersuits-1.12.2-1.0.44.jar               | None                                     |
	| LC    | morecommands                      | 2.1                      | MoreCommands_2.1_mc1.12-1.12.2.jar                | None                                     |
	| LC    | morph                             | 7.1.3                    | Morph-1.12.2-7.1.3.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
	| LC    | mowziesmobs                       | 1.5.4                    | mowziesmobs-1.5.4.jar                             | None                                     |
	| LC    | nevokacore                        | 1.0.2                    | nevoka-core-1.0.2.jar                             | None                                     |
	| LC    | nekeys                            | 0.1.0                    | NotEnoughKeys-0.1.0.jar                           | None                                     |
	| LC    | notenoughwands                    | 1.8.1                    | notenoughwands-1.12-1.8.1.jar                     | None                                     |
	| LC    | oreexcavation                     | 1.4.140                  | OreExcavation-1.4.140.jar                         | None                                     |
	| LC    | projectex                         | 1.2.0.38                 | ProjectEX-1.2.0.38.jar                            | None                                     |
	| LC    | reborncore                        | 3.14.0.455               | RebornCore-1.12.2-3.14.0.455-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | quantumstorage                    | 4.6.8                    | QuantumStorage-1.12-4.6.8.jar                     | None                                     |
	| LC    | redstonearsenal                   | 2.6.3                    | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | refinedexchange                   | 2.1.1                    | refinedexchange-2.1.1.jar                         | None                                     |
	| LC    | refinedstorageaddons              | 0.4.4                    | refinedstorageaddons-0.4.4.jar                    | None                                     |
	| LC    | refinedstoragerequestify          | ${version}               | refinedstoragerequestify-1.12.2-1.0.2-3.jar       | None                                     |
	| LC    | rftools                           | 7.71                     | rftools-1.12-7.71.jar                             | None                                     |
	| LC    | rsinfinitewireless                | 1.2                      | rsinfinitewireless-1.2.jar                        | None                                     |
	| LC    | simplemagnet                      | 1.12.2-1.3.12            | simplemagnet-1.12.2-1.3.12.jar                    | None                                     |
	| LC    | stevescarts                       | 2.4.31.135               | StevesCarts-1.12.2-2.4.31.135.jar                 | None                                     |
	| LC    | techreborn                        | 2.23.0.1001              | TechReborn-1.12.2-2.23.0.1001-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | thermalcultivation                | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics                   | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalinnovation                 | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thutcore                          | 5.21.0                   | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| LC    | thutcore_compat                   | 1.0                      | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| LC    | thuttech                          | 6.1.6                    | thuttech-1.12.2-6.1.6.jar                         | None                                     |
	| LC    | ta                                | 1.0                      | TNT+Amplifier+1.0+1.12.2.jar                      | None                                     |
	| LC    | tnt_utilities                     | 1.2.3                    | tnt_utilities-mc1.12-1.2.3.jar                    | None                                     |
	| LC    | worldedit                         | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LC    | worldhandler                      | 2.2.2                    | WorldHandler-1.12.2-2.2.2.jar                     | d6261bb645f41db84c74f98e512c2bb43f188af2 |
	| LC    | orelib                            | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround                         | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LE    | immersiveengineering              | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| L     | morerefinedstorage                | 1.1.6                    | morerefinedstorage-1.1.6.jar                      | None                                     |
	| L     | techreborn_compat                 | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.1.0.49.jar   | None                                     |
	| UD    | extendedreach_core                | 1.0                      | minecraft.jar                                     | None                                     |
	| UD    | mclib_core                        | 1.0.2                    | minecraft.jar                                     | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
ApotheosisCore (Apotheosis-1.12.2-1.10.2.jar)
  shadows.ApotheosisTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
McLib core mod (mclib-1.0.2-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
p455w0rdc0re (p455w0rdslib-1.12.2-2.2.151.jar)
  p455w0rdslib.asm.ClassTransformer
Extended Reach core mod (extendedreach-1.0-1.12.2.jar)
  mchorse.extendedreach.core.ExtendedReachCMClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
Quark Plugin (Quark-r1.5-166.jar)
  vazkii.quark.base.asm.ClassTransformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6471' Renderer: 'Intel(R) UHD Graphics 630'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E4_pre4
	OptiFine Build: 20190410-123819
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6471
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by PlanetTeamSpeakk** [comment]
Should be fixed with the latest version.
