### ISSUE TITLE
[1.18.2] Game Crashes when opening the Config

### ISSUE THREAD

**Issue by flooorian1** [PlanetTeamSpeakk/MoreCommands#61]
hi,

the game instantly crashed when I open the config. I tried it through "Options > MoreCommands" and through Mod-Menü and the setting button

Game Version: 1.18.2
Fabric 0.13.3-1.18.2
MoreCommands-3.10_1.16.4-22w15a
Modlist: 
![image](https://user-images.githubusercontent.com/99684355/164946631-f49bc28d-f891-4514-9d18-2197ad8ec944.png)

This player seems to have the same problem:
[https://www.curseforge.com/minecraft/mc-mods/morecommands?comment=469](https://www.curseforge.com/minecraft/mc-mods/morecommands?comment=469
)

[crash-2022-04-23_23.31.14-client.txt](https://github.com/PlanetTeamSpeakk/MoreCommands/files/8548640/crash-2022-04-23_23.31.14-client.txt)
.

**Comment by PlanetTeamSpeakk** [comment]
This is known and has been fixed in the upcoming release.
No issue has been made for this bug as it has been reported to me via Discord.
