### ISSUE TITLE
Compat issue with mod The Framework

### ISSUE THREAD

**Issue by curry-ist-guut** [PlanetTeamSpeakk/MoreCommands#7]
Every time try to load a world, it makes it to the blank dirt screen after "loading terrain" and a few seconds later i get the toast notifying me that recipe calculation is complete. And i wait a few seconds until, without fail, my screen says "Shutting down internal server..." and I'm totally pissed after working an hour to get these mods to work together. If you could look into this, it would be great and i can finally get back to playing with 400 mods like i did just 2 days ago. Thanks.

Highlighted the issue in the crash log for convenience. Here you go:
https://pastebin.com/nFPPbCxP

**Comment by PlanetTeamSpeakk** [comment]
Should be fixed already, if not, please reopen.
