### ISSUE TITLE
Local and global chat

### ISSUE THREAD

**Issue by DonorKrovi** [PlanetTeamSpeakk/MoreCommands#74]
I have not yet seen mod implementations for local and global chats, following the example of the Chatty plugin, adding such an opportunity to this mod would be cool

**Comment by PlanetTeamSpeakk** [comment]
Not exactly sure what you mean by local and global chat. Do you mean vicinity chat where you can chat with only nearby players?

**Comment by XionioXMaster** [comment]
> Not exactly sure what you mean by local and global chat. Do you mean vicinity chat where you can chat with only nearby players?

Cool idea, global is a server (general chat) Local (near chat to communicate with a player who is nearby) On the server is sometimes referred to as G, L

**Comment by XionioXMaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/project-essentials-chat

here is a great example, but the mod was abandoned

**Comment by PlanetTeamSpeakk** [comment]
Made this into its own mod, so have fun with that.
1.19.2 only tho, so I hope that's not an issue.
https://www.curseforge.com/minecraft/mc-mods/chattix

**Comment by PlanetTeamSpeakk** [comment]
Also, I am planning on making that mod sort of a modern version of that Essentials Chat project you linked.
So I'll be adding features such as muting, disabling chat, clearing chat, disabling join/leave messages and separate local/global chat too.
