### ISSUE TITLE
Mod comflicts with Apoli/Origins

### ISSUE THREAD

**Issue by TheKaratCake** [PlanetTeamSpeakk/MoreCommands#75]
It's for some reason completely incompatible with Origins and Apoli and it's really bothering me, I love this mod and I'm sad I can't use it

**Comment by PlanetTeamSpeakk** [comment]
Could you send a log? Would save me effort.

**Comment by TheKaratCake** [comment]
Wow I _just_ got a notifcation for this, this was so long ago I don't even remember what this was all about

**Comment by PlanetTeamSpeakk** [comment]
Lol, yes. Just cleaning up the issues and fixing what I can now that I have some time.

**Comment by TheKaratCake** [comment]
It's just so weird, I didn't just get a "closed thread" notification, I recieved the notification for when you commented "Could you send a log? Would save me effort." 2 mintues before I recieved the closed thread notification, which is only a year too late lol

**Comment by PlanetTeamSpeakk** [comment]
I mean, if you can still get a log, I'd be happy to look into it.

**Comment by TheKaratCake** [comment]
I don't even have the pack that did this, that'd be the Fabric pack I made ages ago and since then I've switched computers twice, there might be remenants somewhere but it won't be the latest version unless it hasn't been updated since
