### ISSUE TITLE
Когда выйдет версия без краша?

### ISSUE THREAD

**Issue by DonorKrovi** [PlanetTeamSpeakk/MoreCommands#77]
Последня версия для 1 18 2 крашит сервер, но не клиент, проблема известна уже давно.

**Comment by PlanetTeamSpeakk** [comment]
I've got absolutely no idea what you're trying to say.

**Comment by XionioXMaster** [comment]
> I've got absolutely no idea what you're trying to say.

It seems that 4.0 does not work on the server

**Comment by PlanetTeamSpeakk** [comment]
> > I've got absolutely no idea what you're trying to say.
> 
> It seems that 4.0 does not work on the server

Ah, thanks.
This is known tho, so I'll close this issue.
