### ISSUE TITLE
A set of ideas for fashion

### ISSUE THREAD

**Issue by XionioXMaster** [PlanetTeamSpeakk/MoreCommands#78]
**I haven't fully studied the plugin yet, maybe some ideas have already been implemented**

1 /deathlog player similar to https://www.curseforge.com/minecraft/mc-mods/deathlog A very necessary thing on the server, especially when players die due to mod bugs, you should not trust them in words
2 Improved invsee, some mods use their containers to store things, I believe you can implement support for a full view of the entire inventory as well as the ender of the player's chest
3 /createkit - the ability to customize the issuance of things by slots, it is more convenient than adding everything through the code. In addition, make a default set of Newbie which will be used to issue things to new players (1 visit to the server) 
4 /chatcolor - sets the default color of the player text
5 /killall The command will kill specified types of mobs for example --monster, --animals
6 /maxplayer Changes maximum amount of players who can connect to server - and the permission to circumvent the restriction
7 /openbook Open book gui. Optionally you can provide exact file which needs to be loaded and shown. 
8 /patrol Teleports to random players without repeating same player until all players have been visited. 
9 change /day, /night let the cycle from night to day and vice versa pass smoothly, it will look beautiful.
10 /ride Ride target entity
11 /sit in addition, you can use the support of floor blocks on which the player can sit by right-clicking
https://proxy.spigotmc.org/673d00852dd28f20aee4d49175658424c20a873d?url=https%3A%2F%2Fi.imgur.com%2FRM9ZGHF.png

12 /lay
![image](https://user-images.githubusercontent.com/86433158/194842844-c95af202-67f7-4bcc-b347-6ce4337018e7.png)

13 /playersit
https://proxy.spigotmc.org/bb7556c3a72e34e897dddfe818beb426c7c46706?url=https%3A%2F%2Fi.imgur.com%2FqhJNYoE.png

14 /unloadchunks Unloads chunks from server memory

15 /homes GUI player home
16 /freeze Suspends players actions
17 /actionbarmsg Sends action bar message to player

**Comment by PlanetTeamSpeakk** [comment]
1 Already in the mod, try /deaths.
2 I suppose I could do this, but I don't really see the benefit.
3 Already in the mod.
4 Might do this in Chattix instead.
5 Already in the mod, try /wipeout.
6 I guess I could make a gamerule to bypass this limit, but I don't really see the use in a command to change this value in-game. Especially as it probably wouldn't save it to the disk anyway.
7 Don't get what use this has. Do you mean a command to edit signed books?
8 Don't really see the use in this.
9 Don't really see the use in this.
10 I guess I could do that.
11 You can already right click stairs to sit on them, but I'll leave it at that.
12 Don't really see the use in this.
13 Basically the same as 10
14 I could look into this, I guess. But chunks already get unloaded when they're not needed anyway. Doing it manually would probably just break stuff.
15 Don't really see the use in a GUI for homes
16 I could do this, but it's really hard/near impossible to properly integrate this with mods without breaking stuff.
17 I guess I could do that

**Comment by PlanetTeamSpeakk** [comment]
I will not be implementing any of these ideas as either I wasn't intending to anyway or they are no longer relevant.
