### ISSUE TITLE
There is problems with the mod

### ISSUE THREAD

**Issue by tombjo13** [PlanetTeamSpeakk/MoreCommands#8]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (westerosblocks-4.0.0-beta-1-66.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.68.0-SNAPSHOT-all.jar)
  CWGFarPlaneViewCoreMod (CWGFarPlaneView-0.3.1-core.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1007.0-SNAPSHOT-all.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  JMPatchCoremod (journeymappatcher-1.0-core.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/27/19 8:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CubicGen (cubicgen)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/gen/NoiseGeneratorImproved
	at io.github.opencubicchunks.cubicchunks.cubicgen.ConversionUtils.initFlowNoiseHack(ConversionUtils.java:77)
	at io.github.opencubicchunks.cubicchunks.cubicgen.CustomCubicMod.preInit(CustomCubicMod.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.gen.NoiseGeneratorImproved
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: io/github/opencubicchunks/cubicchunks/cubicgen/asm/mixin/common/accessor/INoiseGeneratorImproved
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: io.github.opencubicchunks.cubicchunks.cubicgen.asm.mixin.common.accessor.INoiseGeneratorImproved
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 884110984 bytes (843 MB) / 2147483648 bytes (2048 MB) up to 19327352832 bytes (18432 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx18G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 37 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                      | Source                                                   | Signature |
	|:----- |:------------------------ |:---------------------------- |:-------------------------------------------------------- |:--------- |
	| LCH   | minecraft                | 1.12.2                       | minecraft.jar                                            | None      |
	| LCH   | mcp                      | 9.42                         | minecraft.jar                                            | None      |
	| LCH   | FML                      | 8.0.99.99                    | forge-1.12.2-14.23.5.2847.jar                            | None      |
	| LCH   | forge                    | 14.23.5.2847                 | forge-1.12.2-14.23.5.2847.jar                            | None      |
	| LCH   | baubles                  | 1.5.2                        | Baubles-1.12-1.5.2.jar                                   | None      |
	| LCH   | betterbuilderswands      | 0.11.1                       | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar          | None      |
	| LCH   | chiselsandbits           | 14.30                        | chiselsandbits-14.30.jar                                 | None      |
	| LCH   | conquest                 | 3.0.2                        | ConquestReforged-3.0.2-mc1.12.2.jar                      | None      |
	| LCH   | blockpalette             | 1.5.0                        | ConquestReforged-3.0.2-mc1.12.2.jar                      | None      |
	| LCH   | connect                  | 1.0.3-mc1.12.2-SNAPSHOT      | ConquestReforged-3.0.2-mc1.12.2.jar                      | None      |
	| LCH   | cubicchunks              | 1.12.2-0.0.1007.0-SNAPSHOT   | CubicChunks-1.12.2-0.0.1007.0-SNAPSHOT-all.jar           | None      |
	| LCH   | cursedlib                | 1.0.0                        | FlameLib-1.12.2-0.0.7.jar                                | None      |
	| LCH   | cubeloader               | 0.0.0                        | CubeLoader-1.12.2-0.0.5_(APIcc).jar                      | None      |
	| LCE   | cubicgen                 | 1.12.2-0.0.68.0-SNAPSHOT     | CubicWorldGen-1.12.2-0.0.68.0-SNAPSHOT-all.jar           | None      |
	| LC    | customspawner            | 3.11.4                       | Custom-Mob-Spawner-Mod-1.12.2.jar                        | None      |
	| LC    | dynamictrees             | 1.12.2-0.9.5                 | DynamicTrees-1.12.2-0.9.5.jar                            | None      |
	| LC    | dynamictreees-cubicaddon | 1.12.2-0.1.1                 | CustomCubic-DynamicTrees-Addon-1.12.2-0.1.1_DT-0.9.5.jar | None      |
	| LC    | thaumcraft               | 6.1.BETA26                   | Thaumcraft-1.12.2-6.1.BETA26.jar                         | None      |
	| LC    | customcubictcfix         | 0.0.0                        | CustomCubicTCFix-1.12.2-0.0.1_(Pre-API).jar              | None      |
	| LC    | cwgfarplaneview          | 0.3.1                        | CWGFarPlaneView-0.3.1.jar                                | None      |
	| LC    | mocreatures              | 12.0.5                       | DrZharks+MoCreatures+Mod-12.0.5.jar                      | None      |
	| LC    | dynamictreestc           | 1.12.2-1.4.1e                | DynamicTreesTC-1.12.2-1.4.1e.jar                         | None      |
	| LC    | flatcoloredblocks        | mc1.12-6.7                   | flatcoloredblocks-mc1.12-6.7.jar                         | None      |
	| LC    | grassburner              | 0.1.0                        | grassburner-0.1.0.jar                                    | None      |
	| LC    | journeymap               | 1.12.2-5.5.4                 | journeymap-1.12.2-5.5.4.jar                              | None      |
	| LC    | journeymappatcher        | 1.0                          | JourneymapPatcher-for-CubicChunks-1.0.jar                | None      |
	| LC    | jaff                     | 1.7_for_1.12                 | Just-a-Few-Fish-Mod-1.12.jar                             | None      |
	| LC    | labyrinth                | 0.5.0                        | labyrinth-0.5.0.jar                                      | None      |
	| LC    | malisiscore              | 1.12.2-6.5.1-SNAPSHOT        | malisiscore-1.12.2-6.5.1.jar                             | None      |
	| LC    | morecommands             | 2.1                          | MoreCommands_2.1_mc1.12-1.12.2.jar                       | None      |
	| LC    | rainboaks                | 1.0.4                        | RainbowOaks-1.12-1.0.4.jar                               | None      |
	| LC    | undergroundbiomes        | 1.3.2                        | UndergroundBiomesConstructs-1.12-1.3.2.jar               | None      |
	| LC    | westerosblocks           | 4.0.0-beta-1-66              | westerosblocks-4.0.0-beta-1-66.jar                       | None      |
	| LC    | winterwonderland         | 1.2.2                        | WinterWonderLand-1.2.2.jar                               | None      |
	| LC    | worldedit                | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-cc4142-SNAPSHOT-dist.jar | None      |
	| LC    | worldeditcuife2          | 2.1.2-mf-1.12.2-14.23.0.2487 | WorldEdit-CUI-Forge-Edition-Mod-1.12.2.jar               | None      |
	| UD    | cubicchunkscore          | @@VERSION@@                  | minecraft.jar                                            | None      |

	Loaded coremods (and transformers): 
FMLLoadingPlugin (westerosblocks-4.0.0-beta-1-66.jar)
  com.westeroscraft.westerosblocks.asm.ClassTransformer
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.68.0-SNAPSHOT-all.jar)
  
CWGFarPlaneViewCoreMod (CWGFarPlaneView-0.3.1-core.jar)
  cwgfarplaneview.core.CWGFPVClassTransformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1007.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
JMPatchCoremod (journeymappatcher-1.0-core.jar)
  io.github.barteks2x.journeymapfix.core.JMPatchTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.71' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 25
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 417.71
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by tombjo13** [comment]
The game don't work with cubic world gen mod or something.
The mod list and status is following:
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID                       | Version                      | Source                                                   | Signature |
|:----- |:------------------------ |:---------------------------- |:-------------------------------------------------------- |:--------- |
| LCH   | minecraft                | 1.12.2                       | minecraft.jar                                            | None      |
| LCH   | mcp                      | 9.42                         | minecraft.jar                                            | None      |
| LCH   | FML                      | 8.0.99.99                    | forge-1.12.2-14.23.5.2847.jar                            | None      |
| LCH   | forge                    | 14.23.5.2847                 | forge-1.12.2-14.23.5.2847.jar                            | None      |
| LCH   | baubles                  | 1.5.2                        | Baubles-1.12-1.5.2.jar                                   | None      |
| LCH   | betterbuilderswands      | 0.11.1                       | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar          | None      |
| LCH   | chiselsandbits           | 14.30                        | chiselsandbits-14.30.jar                                 | None      |
| LCH   | conquest                 | 3.0.2                        | ConquestReforged-3.0.2-mc1.12.2.jar                      | None      |
| LCH   | blockpalette             | 1.5.0                        | ConquestReforged-3.0.2-mc1.12.2.jar                      | None      |
| LCH   | connect                  | 1.0.3-mc1.12.2-SNAPSHOT      | ConquestReforged-3.0.2-mc1.12.2.jar                      | None      |
| LCH   | cubicchunks              | 1.12.2-0.0.1007.0-SNAPSHOT   | CubicChunks-1.12.2-0.0.1007.0-SNAPSHOT-all.jar           | None      |
| LCH   | cursedlib                | 1.0.0                        | FlameLib-1.12.2-0.0.7.jar                                | None      |
| LCH   | cubeloader               | 0.0.0                        | CubeLoader-1.12.2-0.0.5_(APIcc).jar                      | None      |
| LCE   | cubicgen                 | 1.12.2-0.0.68.0-SNAPSHOT     | CubicWorldGen-1.12.2-0.0.68.0-SNAPSHOT-all.jar           | None      |
| LC    | customspawner            | 3.11.4                       | Custom-Mob-Spawner-Mod-1.12.2.jar                        | None      |
| LC    | dynamictrees             | 1.12.2-0.9.5                 | DynamicTrees-1.12.2-0.9.5.jar                            | None      |
| LC    | dynamictreees-cubicaddon | 1.12.2-0.1.1                 | CustomCubic-DynamicTrees-Addon-1.12.2-0.1.1_DT-0.9.5.jar | None      |
| LC    | thaumcraft               | 6.1.BETA26                   | Thaumcraft-1.12.2-6.1.BETA26.jar                         | None      |
| LC    | customcubictcfix         | 0.0.0                        | CustomCubicTCFix-1.12.2-0.0.1_(Pre-API).jar              | None      |
| LC    | cwgfarplaneview          | 0.3.1                        | CWGFarPlaneView-0.3.1.jar                                | None      |
| LC    | mocreatures              | 12.0.5                       | DrZharks+MoCreatures+Mod-12.0.5.jar                      | None      |
| LC    | dynamictreestc           | 1.12.2-1.4.1e                | DynamicTreesTC-1.12.2-1.4.1e.jar                         | None      |
| LC    | flatcoloredblocks        | mc1.12-6.7                   | flatcoloredblocks-mc1.12-6.7.jar                         | None      |
| LC    | grassburner              | 0.1.0                        | grassburner-0.1.0.jar                                    | None      |
| LC    | journeymap               | 1.12.2-5.5.4                 | journeymap-1.12.2-5.5.4.jar                              | None      |
| LC    | journeymappatcher        | 1.0                          | JourneymapPatcher-for-CubicChunks-1.0.jar                | None      |
| LC    | jaff                     | 1.7_for_1.12                 | Just-a-Few-Fish-Mod-1.12.jar                             | None      |
| LC    | labyrinth                | 0.5.0                        | labyrinth-0.5.0.jar                                      | None      |
| LC    | malisiscore              | 1.12.2-6.5.1-SNAPSHOT        | malisiscore-1.12.2-6.5.1.jar                             | None      |
| LC    | morecommands             | 2.1                          | MoreCommands_2.1_mc1.12-1.12.2.jar                       | None      |
| LC    | rainboaks                | 1.0.4                        | RainbowOaks-1.12-1.0.4.jar                               | None      |
| LC    | undergroundbiomes        | 1.3.2                        | UndergroundBiomesConstructs-1.12-1.3.2.jar               | None      |
| LC    | westerosblocks           | 4.0.0-beta-1-66              | westerosblocks-4.0.0-beta-1-66.jar                       | None      |
| LC    | winterwonderland         | 1.2.2                        | WinterWonderLand-1.2.2.jar                               | None      |
| LC    | worldedit                | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-cc4142-SNAPSHOT-dist.jar | None      |
| LC    | worldeditcuife2          | 2.1.2-mf-1.12.2-14.23.0.2487 | WorldEdit-CUI-Forge-Edition-Mod-1.12.2.jar               | None      |

**Comment by PlanetTeamSpeakk** [comment]
Either not a problem with MoreCommands, or was a compatibility problem that has been fixed with the latest version.
If not, please reopen.
