### ISSUE TITLE
Mod conflicts with WorldEdit

### ISSUE THREAD

**Issue by williamconvertino** [PlanetTeamSpeakk/MoreCommands#82]
When used in conjunction with WorldEdit, the MC command /rotate overrides the WE command //rotate. This makes it impossible to rotate in worldedit.

**Comment by PlanetTeamSpeakk** [comment]
Heard of this issue before. It can be fixed by opening the jar file using WinRAR or 7-Zip, going to <your modloader>/com/ptsmods/morecommands/commands/client and deleting RotateCommand.class.

**Comment by PlanetTeamSpeakk** [comment]
I'll probably rename it to rotation or sumn
