### ISSUE TITLE
[Forge, 1.18.2, MoreCommands 4.0] 

### ISSUE THREAD

**Issue by HonzaVinCZ** [PlanetTeamSpeakk/MoreCommands#86]
Dedicated server crashes on launch.

MoreCommands 4.0
ArchitectureAPI 4.10.86

[latest.log](https://github.com/PlanetTeamSpeakk/MoreCommands/files/10135489/latest.log)

**Comment by XXY233** [comment]
Also happens in Forge 1.19.2

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
