### ISSUE TITLE
Mod don't saves warps

### ISSUE THREAD

**Issue by tontonharibo** [PlanetTeamSpeakk/MoreCommands#9]
Each time the server is restarted, the file that saves the warps is recreated and deletes all the warps. 

In addition, other problems occur on the console:

[13:44:34] [MoreCommands/INFO]: Could not load command of class com.ptsmods.morecommands.commands.bind$Commandbind.
[13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: java.lang.NullPointerException
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.ptsmods.morecommands.commands.bind$Commandbind.<init>(bind.java:46)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at java.lang.Class.newInstance(Class.java:442)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.ptsmods.morecommands.Initialize.setupCommandRegistry(Initialize.java:349)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.ptsmods.morecommands.MoreCommands.serverStart(MoreCommands.java:110)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at java.lang.reflect.Method.invoke(Method.java:498)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at java.lang.reflect.Method.invoke(Method.java:498)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at java.lang.reflect.Method.invoke(Method.java:498)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:792)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
> [13:44:34] [Server thread/INFO] [STDERR]: [com.ptsmods.morecommands.Initialize:setupCommandRegistry:355]: at java.lang.Thread.run(Thread.java:748)

I'm waiting for the next version hoping to see these problems fixed.

**Comment by PlanetTeamSpeakk** [comment]
Looking into this for the next version.
The problem with the bind command has been fixed already and will also be released in the next version.

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release. (3.0 port to 1.12)
